application: memo-sm
version: test
runtime: php
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /static
  static_dir: static
  expiration: 2d

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  expiration: 2d

- url: /detailmemobaca.do
  script: detailmemobaca.php

- url: /memobatal.do
  script: memobatal.php

- url: /detailmemo.do
  script: detailmemo.php

- url: /kirimmemo.do
  script: kirimmemo.php

- url: /buatmemo.do
  script: buatmemo.php

- url: /memoviewtest.do
  script: memoviewtest.php

- url: /
  script: lihatmemo.php

- url: /.*
  script: lihatmemo.php

- url: /lihatmemo.do
  script: lihatmemo.php
